### ISSUE TITLE
Status "Zrealizowane"

### ISSUE THREAD

**Issue by jurasjo** [dotpay/WooCommerce2#10]
Czy po poprawnej płatności wtyczka przekaże Woocommerce "info" o tym fakcie aby np. Woocommerce mógł wysłać automatycznie do klienta e-maila "Zamówienie zrealizowane?

Status zamówienia po opłaceniu w = Zrealizowane

**Comment by tbajorek** [comment]
Woocommerce posiada dwa zdefiniowany email "Processing order", który może zostać wysłany w momencie otrzymania płatności. Wystarczy, że go Pan uruchomi w sklepie.
Proszę wejść tutaj:
Woocommerce > Ustawienia > Emaile
i sprawdzić, czy pożądany email jest aktywowany. Jeśli tak jest i jeśli ma Pan skonfigurowaną obsługę wysyłania maili z poziomu sklepu, to klienci powinni otrzymywać informacje o potwierdzeniu zamówienia po dokonaniu wpłaty.

**Comment by MrBloodyJohn** [comment]
Wątek zamknięty, problem uznany za rozwiązany.
