### ISSUE TITLE
Problem z modułem na stronie przejście do kasy

### ISSUE THREAD

**Issue by mediakon** [dotpay/WooCommerce2#11]
Po instalacji Państwa modułu i włączeniu go, w systemie Word Press 4.7.2 z najnowszym WooCommerce po przejściu do kasy i chęci zmiany formy wysyłki cała strona jest blokowana przez skrypt JS z modułu dotpay. Po wyłączeniu modułu dotpay problem znika. Inne włączone moduły płatności to przelew na konto.

Błąd jaki jest generowany:

Uncaught TypeError: jQuery.easing[jQuery.easing.def] is not a function
    at Object.swing (main.min.js?ver=5.0.6:6)
    at init.run (payment_widget.js:37)
    at a (payment_widget.js:37)
    at Function.jQuery.fx.timer (main.min.js?ver=5.0.6:11)
    at hn (payment_widget.js:37)
    at HTMLDivElement.o (payment_widget.js:37)
    at Function.dequeue (payment_widget.js:37)
    at HTMLDivElement.<anonymous> (payment_widget.js:37)
    at Function.each (payment_widget.js:37)
    at p.fn.init.each (payment_widget.js:37)

Co mógłbym ewentualnie przesłać, aby pomóc rozwiązać problem?

Pozdrawiam,
Piotr

**Comment by piotrkunicki** [comment]
Mam ten sam problem, wygląda to na jakiś konflikt skryptu payment_widget.js z pozostałymi skryptami używanymi w motywie... Czy ktoś wie jak rozwiązać ten problem?

**Comment by tbajorek** [comment]
Proszę spróbować najnowszą wersję wtyczki i napisać, czy problem nadal występuje:
https://github.com/dotpay/WooCommerce2/releases/latest

**Comment by betamat** [comment]
"...plugins/woocommerce-dotpay/Gateway/Gateway.php on line 121"
To pojawiało się zamiast strony gdy próbuje się dokonać zakupu. Nie można też wejść w ustawienia WooCommerce.
Wersja 3.0.1
Niestety nie mogłem zainstalować nowej wersji, bo ten problem był również po wyłączeniu poprzedniej - znika strona, zostawał tylko komunikat błędu.
Usunąłem pliki pluginu przez FTP i spróbowałem zainstalować nową wersję. Niestety, efekt to komunikat:
Wtyczka nie mogła zostać włączona, ponieważ spowodowała wystąpienie krytycznego błędu.
Warning: require_once(vendor/simple_html_dom.php) [function.require-once]: failed to open stream: No such file or directory in /DomenaAmmaniaPl/wp-content/plugins/woocommerce-dotpay/Dotpay/Instruction.php on line 28
Fatal error: require_once() [function.require]: Failed opening required 'vendor/simple_html_dom.php' (include_path='.:/:/usr/local/php/pear5:__DIR__') in /DomenaAmmaniaPl/wp-content/plugins/woocommerce-dotpay/Dotpay/Instruction.php on line 28

Proszę o pomoc.

**Comment by tbajorek** [comment]
Ta wersja nie była testowana dla WooCommerce 3. Jeśli chodzi o błąd, jaki opisał  Pan na końcu, może Pan sprawdzić najnowszą wersję [/home/tomek/Pulpit/DOTPAY/WooCommerce2](/home/tomek/Pulpit/DOTPAY/WooCommerce2).
Jeżeli wciąż występują problemy, proszę stworzyć tutaj nowe zgłoszenie, żeby nie było bałaganu.
Pozdrawiam.
