### ISSUE TITLE
Problem with Currencies

### ISSUE THREAD

**Issue by kucherenkodmitriy** [dotpay/WooCommerce2#12]
Hi. i have a problem with currencies detection:
http://prntscr.com/ejc33u
Plugin do not detect any currencies from WooCommerce. 

Can you please help how to fix this problem?

**Comment by tbajorek** [comment]
Hi. What do you mean to say: plugin doesn't detect any currencies?
You shown here a card channel for specific currenciees. If you want to enable it, you have to set those currencies in plugin configuration.
Dotpay offers these available currencies: PLN (default),EUR, USD, GBP, JPY, CZK and SEK.
