### ISSUE TITLE
Problem - "Musisz wybrać kanał płatności"

### ISSUE THREAD

**Issue by zdxh0000** [dotpay/WooCommerce2#16]
Mam problem z wtyczk Dotpay dla WooCommerce. Po wybraniu płatności Dotpay i kliknięciu Kupuję i płacę, dostaję komunikat zwrotny "Musisz wybrać kanał płatności". Nie wiem w czym może tkwić problem. WooCommerce w wersji 3.0.7 a wtyczka Dotpay 3.0.9.

**Comment by wpawel** [comment]
za ten komunikat odpowiada funkcja sprawdzająca czy przy włączonym widgecie wybrano któryś z wyświetlonych kanałów:
https://github.com/dotpay/WooCommerce2/blob/master/Gateway/Dotpay.php#L68
jeśli problem nadal występuje a kanał jest zaznaczony - proszę wysłać takie zgłoszenie wraz ze screenem i adresem strony na adres tech@dotpay.pl

**Comment by wpawel** [comment]
Proszę sprawdzić najnowszą wersję wtyczki:
https://github.com/dotpay/WooCommerce2/releases/tag/v3.0.10

**Comment by tbajorek** [comment]
@zdxh0000 używa Pan wyboru kanałów płatności na stronie sklepu czy w Dotpay?

**Comment by kostek895** [comment]
Dzień dobry,
@wpawel @tbajorek mam ten sam problem. Jest już jakieś rozwiązanie?

Po wyborze płatności, wszystkie kanały znikają i po kliknięciu "Kup" występuje komunikat, że należy wybrać kanał płatności.

**Comment by MrBloodyJohn** [comment]
Proszę zwrócić uwagę na wersję PHP używaną na serwerze. Jeśli kanały płatności chowają się, to oznacza, że został wybrany jeden z nich.
W takim przypadku zalecamy aktualizację modułu do najnowszej wersji:
[https://github.com/dotpay/WooCommerce2/releases/latest](https://github.com/dotpay/WooCommerce2/releases/latest "Najnowsza wersja modułu")
