### ISSUE TITLE
Problem z bramką z najnowszym woocommerce

### ISSUE THREAD

**Issue by dotfortyfour** [dotpay/WooCommerce2#17]
Przy nie zaznaczonym okienku akceptacji regulaminu nie pojawia się komunikat z wc tylko to: **SyntaxError: Unexpected token < in JSON at position 0**

Po sprawdzeniu błędu w debugu przeglądarki dostaję takie coś:

> <b>Notice</b>:  Undefined index: channel in <b>/home/pliz/ftp/plispliz/wp-content/plugins/woocommerce-dotpay/Gateway/Dotpay.php</b> on line <b>69</b><br />
{"result":"failure","messages":"\n<div class=\"woocommerce-messages alert-color medium-text-center\">\n\t<div class=\"message-wrapper\">\n\t\t<ul class=\"woocommerce-error\">\n\t\t\t\t\t\t\t<li><div class=\"message-container container\"><span class=\"message-icon icon-close\"><\/span> Prosz\u0119 zaakceptowa\u0107 wszystkie wymagane zgody<\/div><\/li>\n\t\t\t\t\t\t\t<li><div class=\"message-container container\"><span class=\"message-icon icon-close\"><\/span> Musisz zaakceptowa\u0107 nasz regulamin.<\/div><\/li>\n\t\t\t\t\t<\/ul>\n\t<\/div>\n<\/div>\n","refresh":false,"reload":false}

Dodatkowo po przejściu do bramki klikając płacę pojawia się na ułamek sekundy strona błędu z między innymi:
<img width="1409" alt="screen shot 2017-06-04 at 14 43 01" src="https://cloud.githubusercontent.com/assets/29176108/26761658/26e4406c-4934-11e7-9e76-4f277b28f147.png">

Ten sam tekst pojawia się w mailach wysyłanych po zakceptowaniu płatności klienta.
Czy nie jest to bug spowodowany nową aktualizacją wooocomerca? Jest na to jakieś rozwiązanie przed waszym updatem?

**Comment by tbajorek** [comment]
Jakiej wersji Wordpressa, Woocommerce oraz PHP pan używa?
