### ISSUE TITLE
Błąd JS przy wyborze kanału płatności

### ISSUE THREAD

**Issue by szczav** [dotpay/WooCommerce2#18]
W wersji 3.0.9 /resources/js/payment_widget.js:11165 jest nieprawidłowe wywołanie jquery. W woocommerce 3.1.0 powoduje to bład w przypadku zaznaczenia kanału płatności poprzez kliknięcie checkboxa (a nie grafiki). Checkbox nie jest wtedy zaznaczany.

Trzeba poprawić:
`$(this).parents('.channel-container').click();`
na
`$_dp(this).parents('.channel-container').click();`

**Comment by tbajorek** [comment]
Poprawione. Dziękuję.
