### ISSUE TITLE
"The channel is not set"

### ISSUE THREAD

**Issue by designsoutheast** [dotpay/WooCommerce2#19]
Hi, I'm sorry to leave a message in English, I hope that's OK. 

I'm developing a website for the Polish side of a company, and we are using Dotpay for our payments. When we try to checkout payment with "credit cards by Dotpay", it says:

An error occured
Sorry, your payments during the following error: The channel is not set .
Please contact the seller directly: (...seller's details are here...)
 
or in Polish:

Wystąpił błąd
Przykro nam, w trakcie Twojej płatności wystąpił następujacy błąd: Kanał nie ustawiony.

We have a Dotpay account etc. We're using version 3.0.10 but also tried in version 3.0.8, both have the same message. Using Wordpress 3.0.8.

Thank you very much for your help. I'll translate this message into Polish with Google as well:

Cześć, przepraszam zostawić wiadomość w języku angielskim, mam nadzieję, że jest OK.

Opracowuję stronę internetową dla polskiej strony firmy i używamy Dotpay do naszych płatności. Kiedy próbujemy dokonać płatności za pomocą kart kredytowych Dotpay, mówi:

Wystąpił błąd
Przykro nam, w trakcie Twojej płatności wystąpił następujacy błąd: Kanał nie ustawiony.

Mamy konto Dotpay itp. Używamy wersji 3.0.10, ale też próbowaliśmy w wersji 3.0.8, oba mają tę samą wiadomość. Korzystanie z programu Wordpress 3.0.8.

Bardzo ci dziękuje za pomoc.

**Comment by mateusz-wos** [comment]
Payment cards are not available in the account by default, so the problem appears

Technical Support: tech@dotpay.pl

**Comment by designsoutheast** [comment]
Hi, thank you for your reply. I have emailed tech@dotpay.pl asking for their advice, but could you let me know what I need to do to fix the issue? Is it something I need to change in the settings of the plugin, or is it something we need to configure with Dotpay elsewhere?

Thank you.

Cześć, dziękuję za odpowiedź. Wysłałem email tech@dotpay.pl, prosząc o ich radę, ale czy mógłbyś mi powiedzieć, co muszę zrobić, aby rozwiązać problem? Czy coś trzeba zmienić w ustawieniach wtyczki, czy coś trzeba skonfigurować z Dotpay gdzie indziej?

Dziękuję Ci.

**Comment by MrBloodyJohn** [comment]
Late response, but still. Payment cards are only available through negotiating contract terms with Dotpay. The option to display cards as a payment channel without them being enabled in you Dotpay account will lead to the mentioned error, where it says "The channel is not set". Hope the answear satisfies you.

**Comment by piotr-mamenas** [comment]
Is this still valid and if yes, are you serious?? Every single payments provider gives access to payment cards out of the box without any negotiation. You also mention this on the website, that its available...
