### ISSUE TITLE
DotPay nie aktualizuje statusu płatności

### ISSUE THREAD

**Issue by JurekSIN** [dotpay/WooCommerce2#20]
Dzień dobry,

Nowa wersja wtyczki co prawda dziala z WC w wersji 3 wzwyż, jednak statusy płatności nie są automatycznie aktualizowane w systemie. Musimy wszystko sprawdzać w dotpay i poprawiać ręcznie.

Proszę o pomoc, załączam raport systemu.

``
### WordPress Environment ###

Home URL: //shop.sin.org.pl
Site URL: //shop.sin.org.pl
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.21.0
OpenSSL/0.9.8o

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - Rekomendujemy minimum wersję PHP 5.6. Zobacz: Wymagania WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ✔

### Active Plugins (31) ###

Redux Framework: przez Team Redux – 3.6.5
Autoptimize: przez Frank Goossens (futtta) – 2.2.2
BackWPup: przez Inpsyde GmbH – 3.4.1
iThemes Security: przez iThemes – 6.4.0
Informacja o ciasteczkach: przez dFactory – 1.2.38
Flexible Checkout Fields: przez WP Desk – 1.5.1
Flexible Shipping PRO: przez WP Desk – 1.4
Flexible Shipping: przez WP Desk – 1.9.5
HTTP / HTTPS Remover: przez CONDACORE – 1.5.3
Imsanity: przez Shane Bishop – 2.3.9
InPay WooCommerce: przez InPay S.A. – 1.1
Insert Headers and Footers: przez WPBeginner – 1.4.2
Invisible reCaptcha: przez Mihai Chelaru – 1.1
Free & Simple Contact Form Plugin - PirateForms: przez Themeisle – 1.2.5
Raw HTML: przez Janis Elsts – 1.5
SI Captcha Anti-Spam: przez fastsecure – 3.0.0.20
WPML Multilingual CMS: przez OnTheGoSystems – 3.7.1
Temporary Login Without Password: przez StoreApps – 1.4.2
WooCommerce Dotpay Gateway: przez Dotpay (tech@dotpay.pl) – 3.0.10
WooCommerce Multilingual: przez OnTheGoSystems – 4.2.0
WooCommerce: przez Automattic – 3.1.1
WP File Manager: przez mndpsingh287 – 1.6
WP Meta SEO: przez JoomUnited – 3.4.1
WP Desk Helper: przez WP Desk – 1.2
WPML CMS Nav: przez OnTheGoSystems – 1.4.20
WPML Media: przez OnTheGoSystems – 2.2.0
WPML Sticky Links: przez OnTheGoSystems – 1.4.1
WPML String Translation: przez OnTheGoSystems – 2.5.4
WPML Translation Management: przez OnTheGoSystems – 2.3.1
WPML Widgets: przez Jeroen Sormani – 1.0.6
XML Sitemap & Google News feeds: przez RavanH – 4.7.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Strona sklepu: #4 - /sklep
Koszyk: #5 - /koszyk
Zamówienie: #6 - /zamowienie
Moje konto: #7 - /moje-konto

### Theme ###

Name: OnePress
Version: 1.3.9
Author URL: http://www.famethemes.com
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Archive Template: Twój motyw zawiera plik woocommerce.php
nie możesz zmodyfikować szablonu woocommerce/archive-product.php
ponieważ woocommerce.php ma wyższy priorytet niż archive-product.php. Ma to na celu zapobieganie problemów z wyświetlaniem.

Overrides: –
``

**Comment by isuke01** [comment]
Witam,
Dokładnie ten sam problem  zaobserwowałem.

**Comment by wpawel** [comment]
Próba wysłania notyfikacji z Dotpay była poprawna. Można to sprawdzić w logach dostępnych w panelu Dotpay po zalogowaniu. Problem polega na tym, że w pana sklepie błędnie jest tworzony adres dla zmiennej 'urlc' (oraz url) , który przyjmuje niepoprawną wartość w stylu 'urlc': 'http:////shop.......' czyli zawiera nadmiarową ilość znaków '/'.
Proszę zweryfikować: https://github.com/dotpay/WooCommerce2/blob/master/Gateway/Gateway.php#L179
tam jest podstawiany adres. Powinien mieć on formę  'http://shop....' a nie ' 'http:////shop...'

**Comment by emos321** [comment]
Witam
U mnie to samo. Testowa czysta instalacja WP + woocommerce + bramka i brak aktualizacji płatności. 
Można przetestować na stronie (włączona jest symulacja płatności). 
Nie bardzo się na tym znam a chcę niebawem uruchomić sklep z waszą wtyczką płatności. 

W powiadomieniach dotpay mam informację:


- Typ:

`urlc`

- Adres:

`http://wootest.epizy.com/?wc-api=dotpay_confirm`

- Dane wywołania:

`id=769754&operation_number=M9811-8623&operation_type=payment&operation_status=completed&operation_amount=19.90&operation_currency=PLN&operation_original_amount=19.90&operation_original_currency=PLN&operation_datetime=2017-11-23+21%3A44%3A27&control=2936&description=Nr+zam%C3%B3wienia%3A+2936&email=szpiegcam2%40gmail.com&p_info=Sklep+-+wootest.epizy.com&p_email=szpiegcam2%40gmail.com&channel=36&signature=1415e40ef35534c096bd132f4f428ce58e661e0ef06921b45db8e0291cd715af`

- Dane odpowiedzi:

`<html><body><script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("1434a751576f3e668d3d442b038561f1");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="http://wootest.epizy.com/?wc-api=dotpay_confirm&i=1";</script><noscript>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support</noscript></body></html>`




### WordPress Environment ###

Home URL: http://wootest.epizy.com
Site URL: http://wootest.epizy.com
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 158 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 20 MB
PHP Time Limit: 20
PHP Max Input Vars: 8000
cURL Version: 7.48.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ Baza danych MaxMind GeoIP nie istnieje - Geolokalizacja nie będzie działać. Możesz pobrać i zainstalować ją ręcznie http://dev.maxmind.com/geoip/legacy/geolite/ stąd: . Przewiń w dół do zakładki "Downloads" i pobierz plik "Binary / gzip" obok "GeoLite Country". Pamiętaj
aby rozpakować GeoIP.dat.gz i przesłać tylko plik GeoIP.dat.

Całkowity rozmiar bazy danych: 3.37MB
Rozmiar bazy danych: 3.08MB
Rozmiar indeksu bazy danych: 0.29MB
wp_woocommerce_sessions: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_api_keys: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_attribute_taxonomies: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_downloadable_product_permissions: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_order_items: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_order_itemmeta: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_tax_rates: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_tax_rate_locations: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_shipping_zones: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_methods: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_payment_tokenmeta: Dane: 0.00MB + Indeks: 0.00MB
wp_woocommerce_log: Dane: 0.00MB + Indeks: 0.00MB
wp_commentmeta: Dane: 0.00MB + Indeks: 0.01MB
wp_comments: Dane: 0.16MB + Indeks: 0.04MB
wp_dotpay_instructions: Dane: 0.00MB + Indeks: 0.00MB
wp_dotpay_oneclick_cards: Dane: 0.00MB + Indeks: 0.00MB
wp_links: Dane: 0.00MB + Indeks: 0.00MB
wp_migrator_backups: Dane: 0.83MB + Indeks: 0.00MB
wp_options: Dane: 0.51MB + Indeks: 0.04MB
wp_postmeta: Dane: 0.15MB + Indeks: 0.09MB
wp_posts: Dane: 1.40MB + Indeks: 0.03MB
wp_termmeta: Dane: 0.00MB + Indeks: 0.00MB
wp_terms: Dane: 0.01MB + Indeks: 0.03MB
wp_term_relationships: Dane: 0.01MB + Indeks: 0.02MB
wp_term_taxonomy: Dane: 0.01MB + Indeks: 0.01MB
wp_usermeta: Dane: 0.00MB + Indeks: 0.01MB
wp_users: Dane: 0.00MB + Indeks: 0.01MB

### Post Type Counts ###

attachment: 3
customize_changeset: 2
nav_menu_item: 8
page: 17
post: 60
product: 2
revision: 69
shop_order: 9

### Security ###

Secure connection (HTTPS): ❌Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ✔

### Active Plugins (4) ###

WooCommerce Dotpay Gateway: przez Dotpay (tech@dotpay.pl) – 3.0.12 – Nietestowane z używaną wersją WooCommerce
WooCommerce: przez Automattic – 3.2.5
WordPress Importer: przez wordpressdotorg – 0.6.3
WP Super Cache: przez Automattic – 1.5.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Strona sklepu: #2900 - /sklep/
Koszyk: #2901 - /koszyk/
Zamówienie: #2902 - /zamowienie/
Moje konto: #2903 - /moje-konto/
Regulamin: ❌ Strona nie ustawiona

### Theme ###

Name: Twenty Sixteen
Version: 1.3 – 1.4 jest dostępne
Author URL: https://pl.wordpress.org/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by wpawel** [comment]
Problem polega na tym, że Pana serwer nie przyjmuje notyfikacji wysyłanych poprawnie z Dotpay metodą POST na adres: http://wootest.epizy.com/....
Dlatego zwrotnie pojawia się fragment kodu html zwracany przez Pana serwer zamiast odpowiedzi z modułu płatności.
Proszę o odpowiednią konfigurację serwera (wyłączenie lub konfiguracje AES - Advanced Encryption Standard, które jest tam wdrożone). Dodatkowo proszę zainstalować najnowszą wersje modułu płatności v3.0.13

**Comment by emos321** [comment]
Dziękuję za informację. Aktualnie jest to serwer testowy i nie jest powiązany z docelowym. Na serwerze testowym ([http://wootest.epizy.com](url)) ustawione są również płatności paypal i powiadomienia zwrotne bez problemu zmieniają status. Z wtyczką dotpay status się nie zmienia więc myślałem ze to w niej jest problem (testowane również z wersją 3.0.13). Postaram się przetestować w najbliższym czasie bramkę na serwerze docelowym czy wszystko działa jak powinno.

**Comment by Jalokim** [comment]
Ja również mam problemy z statusami dotpay.
w wersji wtyczki 3.0.9 wszystko było ok. 

Dotatkowe pytanie czy wtyczka dotpay bedzie kompatybilna z WooCommerce 2?
Bo wygląda na to że Dotpay developuje na woocommerce 3. Aktualnie nie mam możliwości upgradu woocommerce do wersji 3, czy to będzie problemem w najbliższej przyszłości?

**Comment by tomaszczado** [comment]
Dołączę się do pytania - ten sam problem co pozostałe osoby i prośbą o informację, co dalej:
- czy powinienem ustawić URLC w konfiguracji DotPay? Jeżeli tak, to na jaki?
- widzę wysyłane powiadomienia urlc z fragmentem kodu w logach zwrotnych - więc rozumiem, że jest coś nietak po stronie sklepu - pytanie, co powinienem sprawdzić

**Comment by MrBloodyJohn** [comment]
Adres URLC jest przesyłany przez moduł płatności jako jeden z parametrów płatności. Domyślnie konfiguracja konta Dotpay nie zezwala na przyjęcie adresu URLC z zewnętrznego źródła. 
Aby umożliwić przyjęcie tego parametru, należy po zalogowaniu do Dotpay w zakładce Ustawienia **odznaczyć**/**wyłączyć** opcję "**Blokuj zewnętrzne URLC**". 

Pytania odnośnie konfiguracji kont Dotpay proszę kierować bezpośrednio na adres tech@dotpay.pl.

**Comment by PistonPL** [comment]
Ten sam problem, zamówienie wciąż oczekuje na zapłatę, po stronie DotPay operacja zrealizowana:

WP: 5.5.1
Woo: 4.5.2
WooCommerce Dotpay Gateway: 3.5.3
