### ISSUE TITLE
Przy próbie instalacji wtyczki

### ISSUE THREAD

**Issue by polo195pl** [dotpay/WooCommerce2#21]
Woo i WP na najnowszej wersji. 
Fatal error: Cannot declare class simple_html_dom_node, because the name is already in use in /wp-content/plugins/woocommerce-dotpay/vendor/simple_html_dom.php on line 115

**Comment by wpawel** [comment]
proszę odinstalować plugin, następnie usunąć z poziomu serwera (ssh, ftp) ewentualne  pozostałości folderu z pluginem, katalog : /wp-content/plugins/**woocommerce-dotpay**
Po tych zabiegach proszę przeprowadzić ponowną próbę instalacji najnowszej wersji pluginu,

**Comment by wpawel** [comment]
Problem nie powinien występować w wersji [3.0.14](https://github.com/dotpay/WooCommerce2/tree/v3.0.14).
Mógł się pojawiać w przypadku użycia klasy 'simple_html_dom_node' w innym zainstalowanym module w Woocommerce.
