### ISSUE TITLE
Aktualizacja wtyczki

### ISSUE THREAD

**Issue by AleksanderMossly** [dotpay/WooCommerce2#22]
Mam zainstalowaną wersję 3.0.11. Gdy zainstalowałem i uruchomiłem wersję 3.0.12 otrzymałem informację:

Wtyczka nie mogła zostać włączona, ponieważ spowodowała wystąpienie krytycznego błędu.

Fatal error: Cannot redeclare is_session_started() (previously declared in /home/<sklep>/domains/<sklep>/public_html/wp-content/plugins/WooCommerce2-master/woocommerce-dotpay.php:21) in /home/<sklep>/domains/<sklep>/public_html/wp-content/plugins/woocommerce-dotpay/woocommerce-dotpay.php on line 21

Czy powinienem usunąć wcześniejszą wersję wtyczki? Nie ma jakiejś możliwości bardziej 'bezbolesnej' aktualizacji?

**Comment by wpawel** [comment]
Plugin należy instalować zgodnie z instrukcją!

Proszę nie używać paczki generowanej pod przyciskiem "Clone or download" tylko linków do paczek pluginu dostępnych pod adresem: [https://github.com/dotpay/WooCommerce2/releases/latest](https://github.com/dotpay/WooCommerce2/releases/latest)
Ostatni link do wersji pluginu : [3.0.12](https://github.com/dotpay/WooCommerce2/releases/download/v3.0.12/woocommerce-dotpay.3.0.12.zip)
Przed instalacją proszę usunąć najpierw wszystkie kopie pluginu Dotpay ze sklepu.
