### ISSUE TITLE
Płatność czeka na potwierdzenie przez Dotpay

### ISSUE THREAD

**Issue by michaell94** [dotpay/WooCommerce2#25]
W przypadku gdy jQuery nie jest ładowane w nagłówku(`<head>`) a w stopce, na dole dokumentu, wtyczka zawiesza się na etapie:

"Płatność czeka na potwierdzenie przez Dotpay"

Chwile mi zeszło odnalezienie dlaczego tak się dzieje, dlatego zostawiam informacje dla innych mających ten problem. :)

**Comment by jakubLW** [comment]
Jak mogę przenieść ładowanie jQuery płatności do sekcji <head>?

**Comment by michaell94** [comment]
Dodaj ładowanie jQuery pomiędzy znacznikami <head></head> bo wordpress domyślnie ładuje je w stopce.

**Comment by mbed92** [comment]
Problem nie został rozwiązany - dodanie jQuery w head nie jest rozwiązaniem. Czy ktoś dał radę naprawić ten problem? Korzystam z najnowszej wersji wtyczki.

**Comment by marcinpl87** [comment]
@mbed92 spróbuj:
w panelu dotpay przejdź do menu Ustawienia → Powiadomienia → Konfiguracja urlc i **odznacz** opcję „Blokuj zewnetrzne urlc”. Pole adres Urlc pozostaw puste.
**Odznacz** też checkboxy związane z https i certyfikatem.

(u mnie pomogło)

**Comment by lamik** [comment]
> @mbed92 spróbuj:
> w panelu dotpay przejdź do menu Ustawienia → Powiadomienia → Konfiguracja urlc i **odznacz** opcję „Blokuj zewnetrzne urlc”. Pole adres Urlc pozostaw puste.
> **Odznacz** też checkboxy związane z https i certyfikatem.
> 
> (u mnie pomogło)

Dzisiaj też trochę powalczyłem z problemem i pomogło to samo co u Ciebie - odznaczenie external urlc

**Comment by MrBloodyJohn** [comment]
Temat zamknięty, problem uznany za rozwiązany.

Rozwiązanie:

> @mbed92 spróbuj:
> w panelu dotpay przejdź do menu Ustawienia → Powiadomienia → Konfiguracja urlc i **odznacz** opcję „Blokuj zewnetrzne urlc”. Pole adres Urlc pozostaw puste.
> ~~**Odznacz** też checkboxy związane z https i certyfikatem.~~
> 
> (u mnie pomogło)

Brak potwierdzeń najczęściej związany jest z opcją **Blokuj zewnętrzne urlc**/**Block external urlc**. 
Jeśli nie ma certyfikatu SSL na stronie, a opcje **HTTPS verify** i **SSL certificate verify** są zaznaczone, to płatność się nie utworzy i wyświetlony zostanie komunikat błędu.

**Comment by mbed92** [comment]
No i niestety problem powrócił tylko kompletnie nie rozumiem dlaczego (w tym czasie byłem na wakacjach - nic nie robiłem).

Mam w panelu Dotpay odznaczone HTTPS i SSL, mam odznaczone blokowanie zewnętrznego URLC. W htcaccess dodana została linia (zgodnie z sugestią supportu dotpay):
```php
php_value max_execution_time 1800
```

Niestety to nie pomogło. Skierowany zostałem do zenboxa, u którego mam hosting - też nic. Wiadomo tylko, że połączenie wychodzące z serwera do Dotpay jest prawidłowe. Błąd występuje podczas sprawdzania statusu operacji. Zwracana jest bowiem wiadomość:
```
timer_off Błąd płatności
```

Nie mam już pomysłów gdzie może leżeć błąd.

**Comment by MrBloodyJohn** [comment]
Informacja z logów mówi jedynie o parametrach wymaganych do specyficznego kanału płatności, nie ma ona znaczenia dla występującego błędu. 

Występuje tu problem z adresem IP, z którego przekazywane jest potwierdzenie - rozpoznawany jest adres IP zendbox'a. 
Modyfikację modułu można przeprowadzić we własnym zakresie: zmieniając warunki weryfikacji adresu IP (dodanie zgłaszanego IP) lub też pomijając weryfikację kompletnie (niezalecane). Kod odpowiedzialny za weryfikację adresu IP znajduje się pod tym [linkiem](https://github.com/dotpay/WooCommerce2/blob/master/Gateway/Gateway.php#L621).
Z racji, że jest to zmiana indywidualna (dotycząca specyficznego przypadku), nie zostanie wdrożona w ogólnodostępnym wydaniu.

**Comment by mbed92** [comment]
Dziękuję @MrBloodyJohn 
Problem leżał dokładnie w tej linii, którą zalinkowałeś. Adres IP zwracany przez _getClientIp()_ to adres serwera Zenbox'a i nie pasował on do DOTPAY_IP ani OFFICE_IP. O ile pierwszy adres to adres serwera Dotpay, to ten drugi nie wiem co to za adres.

```php
// Office Dotpay IP address
const OFFICE_IP = '77.79.195.34';
``` 

Tak czy siak dodałem weryfikację IP mojego serwera i teraz jest już ok. Dzięki za pomoc i pozdrawiam.
