### ISSUE TITLE
Polylang + Dotpay - Problem, nie ładuje angielskiego

### ISSUE THREAD

**Issue by onlyway** [dotpay/WooCommerce2#27]
Witam
przy użyciu polylang niestety nie jestem w stanie uzyskać języka angielskiego po przestawieniu na niego na froncie strony. Czy na tą okazję jest jakiś hook do functions.php, którego można użyć w tym celu?

**Comment by wpawel** [comment]
problem dotyczyc mół właczonej wersji testowej  w konfiguracji sklepu.
naprawione w wersji [v3.2.2](https://github.com/dotpay/WooCommerce2/tree/v3.2.2)
Proszę o potwierdzenie.

**Comment by MrBloodyJohn** [comment]
Fixed in [v3.2.2](https://github.com/dotpay/WooCommerce2/tree/v3.2.2)
