### ISSUE TITLE
Status zamówienia po płatności | Zrealizowane > w trakcie realizacji

### ISSUE THREAD

**Issue by likeagency** [dotpay/WooCommerce2#29]
Wtyczka po płatności dotpay ustawia status zamówienia na Zrealizowane. Wg. prawa jest zrealizowane jak zostało dostarczone - a nie po otrzymaniu płatności. Czy jest możliwość poprawy z poziomu wtyczki? 

Jak nie to czy możliwy jest jakiś fix który sami możemy zastosować w kodzie?

**Comment by likeagency** [comment]
Jakaś możliwość naprawy tego?

**Comment by wpawel** [comment]
Nieprawda: wtyczka ustawia status zamówienia po potwierdzeniu płatności :  "W trakcie realizacji":
link: [Gateway/Gateway.php#L36](https://github.com/dotpay/WooCommerce2/blob/master/Gateway/Gateway.php#L36)
` const STATUS_COMPLETED = 'processing';` 
W kolejnych wersjach wtyczki planowane jest dodanie możliwości zmiany domyślnego statusu zamówienia z poziomu ustawień.

**Comment by likeagency** [comment]
Aktualizacja wtyczki naprawiłą ten bład.
