### ISSUE TITLE
Fatal error przy próbie aktywowania wtyczki

### ISSUE THREAD

**Issue by AngryBytesPL** [dotpay/WooCommerce2#30]
W 57 linijce pliku: woocommerce-dotpay/templates/oc_manage.phtml jest użyty krótki znacznik rozpoczęcia php, który wywala błąd na niektórych serwerach.

**Comment by maciles** [comment]
Ja mam:

Parse error: syntax error, unexpected end of file in .../woocommerce-dotpay/templates/oc_manage.phtml on line 58

i też nie mogę aktywować wtyczki. Ale DotPay mimo wysłanych maili milczy :/

**Comment by wpawel** [comment]
Problem występować może jeśli w php.ini jest `short_open_tag = Off`.
Poprawione w aktualnej wersji. Przygotowywana jest nowa wersja z dodatkowymi poprawkami.
