### ISSUE TITLE
Podwójna etykieta w zakładce płatności

### ISSUE THREAD

**Issue by alpha-leonis** [dotpay/WooCommerce2#35]
W zakładce płatności etykieta nad formami płatności wyświetla się podwójnie jak na poniższym obrazku:

![image](https://user-images.githubusercontent.com/10750441/44660783-fe6fcc00-aa08-11e8-92e8-209053bd5ead.png)

**Comment by MrBloodyJohn** [comment]
Pierwszy komunikat jest innej klasy/wagi jak drugi i świadczy o nie aktywnym module płatności. Drugi służył jedynie informacji/przypomnieniu - jest możliwe jego usunięcie, gdy moduł jest aktywny (pull request powyżej). Można to również zrobić we własnym zakresie.
