### ISSUE TITLE
Brak możliwości aktualizacji z poziomu Wordpressa + źle podpięty link w komunikacie

### ISSUE THREAD

**Issue by alpha-leonis** [dotpay/WooCommerce2#36]
Nie ma możliwości aktualizacji modułu z poziomu Wordpressa + w komunikacie, który się wyświetla, link prowadzi do niewłaściwej (starej) wersji release

**Comment by MrBloodyJohn** [comment]
Z poziomu Wordpress istnieje możliwość pobrania najnowszej wersji modułu płatności, odnośniki prowadzą do odpowiednich plików.
