### ISSUE TITLE
Problem ze statusem transakcji

### ISSUE THREAD

**Issue by tomiflake** [dotpay/WooCommerce2#39]
I tak w kółko. Jak można to rozwiązać? Wysyłany jest status OK plus jakieś znaczki.

![dot1](https://user-images.githubusercontent.com/44409216/47376061-ff179c80-d6f1-11e8-8778-8011591fd51a.png)
![dot2](https://user-images.githubusercontent.com/44409216/47376070-02ab2380-d6f2-11e8-9563-39cbc109d108.png)

**Comment by MrBloodyJohn** [comment]
Zgodnie z wymaganiami modułu płatności: 

> - PHP min. 5.6, recommended: >7.0 


proszę zmienić wersję PHP na odpowiednią i przeinstalować moduł płatności używając [najnowszego wydania.](https://github.com/dotpay/WooCommerce2/releases/latest)
