### ISSUE TITLE
Obsługa automatycznych zwrotów

### ISSUE THREAD

**Issue by Kerrex** [dotpay/WooCommerce2#45]
Nie udało mi się znaleźć takiej opcji stąd pytanie - czy moduł obsługuje automatyczne zwroty z poziomu Woocommerce? Jeśli nie, to czy są plany dodania tej funkcjonalności?

**Comment by MrBloodyJohn** [comment]
Na ten moment moduł Dotpay nie obsługuje zwrotów z poziomu Woocommerce i wprowadzenie takiej funkcjonalności nie zostało zaplanowane na najbliższe wydania.
