### ISSUE TITLE
W przypadku przerwanej płatności nie aktualizuje statusu zamówienia

### ISSUE THREAD

**Issue by edikay** [dotpay/WooCommerce2#46]
Dotyczy zamówień które zostały przerwane, np. zamknięta strona wyboru płatności lub logowania do banku, jeżeli kliknę na stronie płatności w banku "Anuluj" to poprawnie zmienia status zamówienia na "Nieudane". Udane płatności są poprawnie oznaczane.

**Comment by MrBloodyJohn** [comment]
Jest to zachowanie systemu Dotpay, nie modułu płatności. W przypadku kliknięcia "Anuluj" moduł otrzymuje informację o odrzuceniu płatności, natomiast gdy nie ma żadnej akcji - nie ma powiadomienia, co też tłumaczy brak zmiany statusu.
