### ISSUE TITLE
"Przelewy online oraz Płatności gotówkowe"

### ISSUE THREAD

**Issue by bawsieznami** [dotpay/WooCommerce2#47]
Dzień dobry,

Korzystam z dotpaya i waszej wtyczki WooCommerce Dotpay Gateway, mam problem nie jestem w stanie usunąć płatnośći (### Przelewy online oraz Płatności gotówkowe)  i która to nie działa (a w Konfiguracji płatności) jest wyłączona, moge prosić o pomoc?

Pozdrawiam
Dawid Szyja
strona: https://specki.pl

**Comment by MrBloodyJohn** [comment]
W jakim sensie "usunąć"? Czy chodzi o to, że wyświetla się ona w zakładce *WooCommerce -> Ustawienia -> Płatności*? Jeśli tak, to jest to działanie zamierzone, opcja ta ma się wyświetlać w tym miejscu. 

Nie ma konieczności usuwania tej pozycji, wystarczy, że jest nieaktywna/wyłączona.

**Comment by slawekl** [comment]
Witam nie wiem czy to ten sam problem w drugą stronę. Próbuje uruchomić płatności online, w adminie są nie aktywne i nie da się ich włączyć. W formularzu pojawiają się i po sekundzie znikają.

**Comment by MrBloodyJohn** [comment]
Bardzo proszę załączyć zrzut ekranu z:

 1. Okna _Płatności_ WooCommerce, gdzie widoczne są metody płatności.
 2. Konfiguracji Dotpay w WooCommerce (proszę ukryć/usunąć dane takie jak PIN, użytkownik i hasło).

**Comment by slawekl** [comment]
<img width="1096" alt="Zrzut ekranu 2019-04-8 o 12 23 54" src="https://user-images.githubusercontent.com/9512918/55717869-951e5580-59fa-11e9-87ce-5f5ec4fb6b4e.png">
<img width="876" alt="Zrzut ekranu 2019-04-8 o 12 24 33" src="https://user-images.githubusercontent.com/9512918/55717870-951e5580-59fa-11e9-8e1e-4e4bcf4ad7b4.png">
<img width="770" alt="Zrzut ekranu 2019-04-8 o 12 24 42" src="https://user-images.githubusercontent.com/9512918/55717871-95b6ec00-59fa-11e9-9deb-013959fe80f3.png">
<img width="763" alt="Zrzut ekranu 2019-04-8 o 12 25 01" src="https://user-images.githubusercontent.com/9512918/55717872-95b6ec00-59fa-11e9-97c2-c1461f580dfe.png">
<img width="294" alt="Zrzut ekranu 2019-04-8 o 12 31 25" src="https://user-images.githubusercontent.com/9512918/55717873-95b6ec00-59fa-11e9-8f9a-57d975cc1e9c.png">

**Comment by MrBloodyJohn** [comment]
Kanały płatności udostępnione przez Dotpay są niewidoczne, ponieważ w konfiguracji modułu podał Pan walutę PLN, dla której główna metoda płatności będzie **niedostępna**. Jeśli usunie Pan tą walutą z konfiguracji to kanały płatności zostaną wyświetlone.

**Comment by slawekl** [comment]
Super działa, dzięki. Nie podawałem waluty była domyślnie ustawiona.
