### ISSUE TITLE
Aktualizacja wtyczki

### ISSUE THREAD

**Issue by TCMz** [dotpay/WooCommerce2#48]
Witam
Jaka jest aktualna procedura aktualizacji wtyczki ?
Gdy usuwam starą wersję to automatycznie kasują się strony związane z wtyczką co jest dla mnie kłopotliwe ponieważ przy instalacji nowej wersji muszę od nowa aktualizować powstałe na nowo strony.

**Comment by MrBloodyJohn** [comment]
W celu aktualizacji modułu należy wykonać następujące kroki:

 - Wyłączyć i usunąć moduł z poziomu menu _**Wtyczki**_.
 - Zainstalować nową wersję poprzez opcję _**Dodaj nową**_.

Przy instalacji moduł tworzy katalog w plikach strony, dlatego wymagana jest wcześniejsze odinstalowanie poprzedniej wersji.

**Comment by TCMz** [comment]
> W celu aktualizacji modułu należy wykonać następujące kroki:
> 
> * Wyłączyć i usunąć moduł z poziomu menu _**Wtyczki**_.

Podczas usuwania wtyczki z poziomu menu automatycznie są kasowane strony.
-Szczegóły twojej płatności
-Sprawdzenie statusu płatności
-Moje zapisane karty

Po ponownej instalacji znowu te same strony są tworzone automatycznie.
Problem w tym że jeżeli mam na tych stronach wprowadzone jakieś zmiany to muszę po każdej aktualizacji wprowadzać wszystko na nowo. Czy jest możliwość żeby wtyczka nie kasowała stron podczas aktualizowania?

**Comment by MrBloodyJohn** [comment]
Niestety nie ma możliwości usunięcia jedynie części treści, które zostały utworzone przez moduł, natomiast zawsze można zapisać zawartość stron, które zostaną zmodyfikowane/usunięte przy reinstalacji wtyczki.
