### ISSUE TITLE
ID zamówienia w dotpay gdy w ID jest zmienione w WC 

### ISSUE THREAD

**Issue by 12maup** [dotpay/WooCommerce2#53]
Witam,

Klient zmienił defaultowe id zamówień na cykliczne. A więc post id !== id zamówienia w panelu admina i mejlach do klientów. Jest to o tyle kłopotliwe że klient dostaje mejla z dotpay z innym numerem zamówienia niż to które ma w mejlu potwierdzającym zakup.

Sprawę udało mi się rozwiązać:

C:\Users\Lenovo\Documents\RebelWeb\mumla\mumla.pl\wp-content\plugins\woocommerce-dotpay\Dotpay\Payment.php

```
    public function getDescription()
    {
        return __('Order ID: ', 'dotpay-payment-gateway') . esc_attr($this->getLegacyOrderId_2($this->getOrder()));
    }
```

gdzie getLegacyOrderId_2 to:

```
    private function getLegacyOrderId_2($orderObject)
    {
        if (method_exists($orderObject, 'get_id')) {
      //     return $orderObject->get_id();
            return $orderObject->get_order_number();
        } else {
            return $orderObject->id;
        }
    }
```
A więc get_id() zamieniłem na get_order_number();

Działa, ale może warto by było uwzględnić to w kolejnej aktualizacji?

Pozdrawiam,
Piotr Wiktor.

**Comment by wpawel** [comment]
Dzięki za sugestię.
Dodano w nowej wersji: [v3.2.5](https://github.com/dotpay/WooCommerce2/tree/v3.2.5)
