### ISSUE TITLE
Metoda płatności Dotpay <small>(szybkie płatności)</small> 

### ISSUE THREAD

**Issue by matdabrowski** [dotpay/WooCommerce2#56]
Cześć, po ostatniej aktualizacji do wersji 3.2.6
Metoda płatności wyświetla się w zamówieniu ze znacznikami htmla

![image](https://user-images.githubusercontent.com/761676/66118362-7fb76c00-e5d6-11e9-991f-f23b307c9426.png)

Tak zapisuje się też w bazie, bo po wyeksportowaniu zamówienia z woocommerce jest tak samo.

To, że się wyświetla źle to pół biedy, ale że się eksportuje w ten sposób, to po prostu więcej pracy.

**Comment by wpawel** [comment]
Poprawione w nowszej wersji [v3.2.7](https://github.com/dotpay/WooCommerce2/tree/v3.2.7) (beta)
