### ISSUE TITLE
Duża czcionka akceptacji regulaminu

### ISSUE THREAD

**Issue by dragowicz192** [dotpay/WooCommerce2#59]
W którym miejscu można zmniejszyć czcionkę gdy mamy wybór płatności i trzeba zaakceptować regulamin jest ona bardzo przytłaczająca wielkością

**Comment by wpawel** [comment]
za styl Regulaminu odpowiada klasa "dotpay_agreements", która zdefiniowana jest w arkuszu [resources/css/dotpay_payment_form.css](https://github.com/dotpay/WooCommerce2/blob/master/resources/css/dotpay_payment_form.css#L1)
Ustawienia definiują 90% wielkości standardowej czcionki, można to zmienić na wartość liczbową w px jeśli główna czcionka jest zbyt duża.
