### ISSUE TITLE
session_start cache

### ISSUE THREAD

**Issue by pablito07** [dotpay/WooCommerce2#69]
woocommerce-dotpay.php:172

woocommerce-dotpay.php:190 funkcja init_woocommerce_dotpay_session_start

uruchamianie w ten sposób session_start() uniemożliwia działanie całkowicie cache po stronie serwera.

Sesja uruchamiana jest dla każdej osoby wchodzącej na stronę, co nie powinno mieć miejsca.

**Comment by wpawel** [comment]
W tym zakresie dokonano zmiany w najnowszym kandydacie do wydania: v3.5.0.rc, do pobrania:
[woocommerce-dotpay_3.5.0_rcX](https://github.com/dotpay/WooCommerce2/releases/latest)

**Comment by wpawel** [comment]
[v3.5.1](https://github.com/dotpay/WooCommerce2/tree/v3.5.1)
