### ISSUE TITLE
Wersja 3.5.1 daje komunikat "W witrynie wystąpił błąd krytyczny." przy checkoucie

### ISSUE THREAD

**Issue by mactez** [dotpay/WooCommerce2#72]
Po aktualizacji dotpay do 3.5.1 zaczęło sypać przy checkout błędem
![1](https://user-images.githubusercontent.com/39680625/86402401-0c996e00-bcac-11ea-8653-b1c35259063f.png)

W logach wordpressa:
[02-Jul-2020 19:28:56 UTC] PHP Fatal error:  Uncaught Exception: Nieprawidłowe zamówienie. in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:103
Stack trace:
#0 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
#1 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(112): WC_Data_Store->read(Object(WC_Order))
#2 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php(1367): WC_Abstract_Order->__construct(2301)
#3 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php(334): Dotpay_Payment->getOrder()
#4 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/form/standard.phtml(47): Dotpay_Payment->getAmountForWidget()
#5 /ho in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 103
[02-Jul-2020 19:29:21 UTC] PHP Notice:  Undefined index: channel in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Gateway/Dotpay.php on line 82
[02-Jul-2020 19:29:28 UTC] PHP Notice:  Undefined index: channel in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Gateway/Dotpay.php on line 82
[02-Jul-2020 19:29:43 UTC] PHP Fatal error:  Uncaught Exception: Nieprawidłowe zamówienie. in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:103
Stack trace:
#0 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
#1 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(112): WC_Data_Store->read(Object(WC_Order))
#2 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php(1367): WC_Abstract_Order->__construct(2301)
#3 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/Dotpay/Payment.php(334): Dotpay_Payment->getOrder()
#4 /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce-dotpay/form/standard.phtml(47): Dotpay_Payment->getAmountForWidget()
#5 /ho in /home/onlinere/domains/onlinerecepta.pl/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 103

Nie jestem developerem, co mógłbym sprawdzić jeszcze żeby dać Państwu więcej informacji o tym gdzie wysypała się wtyczka ?

Pozdrawiam

**Comment by mactez** [comment]
po powrocie do 3.3.1 wszystko działa jak należy

**Comment by wpawel** [comment]
Pod adresem https://wordpress.org/support/topic/fatal-error-uncaught-exception-exception-with-message-invalid-order/ opisany jest fix, jaki można zrobić w takim przypadku dla woocommerce.
Proszę o test czy był skuteczny.
Póki co to jedyny jak na razie taki zgłoszony przypadek, nie udało nam się powtórzyć takiego błędu.

**Comment by mactez** [comment]
Dodam tylko, że istnieje szansa, że wszystko zaczęło się psuć, po tym jak dodałem ręcznie jedno zamówienie do woocommerce (klient zapłacił poza serwisem, a chciałem mieć wszystko uporządkowane w jednym miejscu).  Dodanie zamówienia nastąpiło przez następujący ciąg kroków w panelu administracyjnym: Woocommerce -> zamówienia -> dodaj zamówienie -> i tutaj w rubryce płatność ręcznie wpisałem nowego klienta, jego dane adresowe, metoda płatności dotpay i ID Transakcji przekopiowałem z panelu dotpay.pl (M2527-95991), status zamówienia ustawiony na "W trakcie realizacji".

Jest to jedyna rzecz jaką robiłem w panelu administracyjnym tego dnia, wcześniej plugin dotpay w wersji 3.5.1 działał należycie i zamówienia klienci składali poprawnie.

**Comment by Konstanty-Martyniuk** [comment]
Dzień dobry,
po aktualizacji występuje ten sam błąd jak powyżej.

**Comment by GaganMedia** [comment]
Potwierdzam, u mnie checkout też wywala. Wyświetla w jakiejś ramce bez header. Wersja 3.3.1 działa normalnie.

**Comment by Konstanty-Martyniuk** [comment]
> Potwierdzam, u mnie checkout też wywala. Wyświetla w jakiejś ramce bez header. Wersja 3.3.1 działa normalnie.

Wersja 3.3.1 działa normalnie, starsze nie pokażą błędu, ale na samym końcu przycisk "zapłać" będzie nieaktywny.

**Comment by GaganMedia** [comment]
> > Potwierdzam, u mnie checkout też wywala. Wyświetla w jakiejś ramce bez header. Wersja 3.3.1 działa normalnie.
> 
> Wersja 3.3.1 działa normalnie, starsze nie pokażą błędu, ale na samym końcu przycisk "zapłać" będzie nieaktywny.

Dzięki za info.
