### ISSUE TITLE
Aktualizacja do 3.5.1

### ISSUE THREAD

**Issue by ELkoos** [dotpay/WooCommerce2#73]
Witam, w trakcie aktualizacji/wgrywania wtyczki na serwer dostaję informację o już istniejącym katalogu wtyczki. Czy to normalne, czy jednak nie powinno się to odbywać na zasadzie detekcji już istniejącej instalacji i wykonaniu aktualizacji, tak jak w innych wtyczkach? Czy wobec tego, mam wyrzucić całą poprzednią konfigurację i konfigurować ją od nowa?

**Comment by wpawel** [comment]
Tak, przed instalacją tej wersji, proszę w pierwszej kolejności odinstalować poprzednia wersję, lub osunąć sam katalog woocommerce-dotpay/.
