### ISSUE TITLE
Błąd wtyczki

### ISSUE THREAD

**Issue by adamboek** [dotpay/WooCommerce2#74]
![error](https://user-images.githubusercontent.com/13335384/87317111-dc14c800-c526-11ea-8fe4-df08de986d76.jpg)

Aktualna wersja wtyczki 3.51 przy Woocommerce 4.3.0, błąd wyskoczył po aktualizacji Dotpaya, jeśli trzeba więcej danych, piszcie. Przy wersji 3.4.0 działa normalnie z jednym małym błędem: po zmianie płatności nie odświeża się order review.

**Comment by dotM4rio** [comment]
Proszę o więcej informacji. Do weryfikacji pomocny będzie adres url, możesz podesłać go na tech@dotpay.pl

**Comment by marcinozimek** [comment]
Dzień dobry. Czy problem nadal występuje? Z tego co zauważamy przy testowym zamówieniu to po wyborze kanału z widgetu znika komunikat "Nie wybrano kanału płatności".
![koszyk](https://user-images.githubusercontent.com/19753088/87538855-39328a00-c69d-11ea-9122-4f1b057f725d.JPG)

![wybor_kanalu](https://user-images.githubusercontent.com/19753088/87538864-3c2d7a80-c69d-11ea-8c3c-8c2e4e35eeb1.JPG)

**Comment by adamboek** [comment]
Bardzo dziękuję za odpowiedź. Przepraszam, że musieli się państwo
fatygować, zapomniałem o tym, że wtyczka LSCache łączyła i minifikowała
skrypty JS, stąd wyskakujący błąd na stronie. Teraz wszystko działa
poprawnie. Jeszcze raz dziękuję i pozdrawiam.

śr., 15 lip 2020 o 13:15 Marcin Ozimek <notifications@github.com>
napisał(a):
