### ISSUE TITLE
?wc-api=dotpay_status zwraca - 0 i nie przekierowuje pomyślnej płatności na 'thank you page'

### ISSUE THREAD

**Issue by ama93** [dotpay/WooCommerce2#75]
Witam. 

nie wiem dlaczego ale po dokonanej poprawnie transakcji nie dostaje przekierowania na stronę podziękowania i po 2 minutach dostaje info o przekroczonym czasie odpowiedzi. testując lokalnie i symulując płatność widzę, że dostaje kod - 0 na endpoint http://localhost:8080/?wc-api=dotpay_status zamiast 1. 

![image](https://user-images.githubusercontent.com/12041395/88922690-bef32f80-d270-11ea-979c-bcbb01458fb3.png)

Używam najnowszej wersji wtyczki - 3.5.1 i wp- 5.4.2 oraz wc najnowszy.

Mogę wiedzieć dlaczego tak się dzieje i czy coś jest do poprawienia? Niedawno zmieniałem serwer może czegoś brakuje. 

Dzieki!

**Comment by wpawel** [comment]
Notyfikacje z Dotpay o statusie transakcji wysyłane metodą POST są na adres sklepu. Oczywistym jest fakt, że dla adresu 'localhost' Dotpay nie wyśle notyfikacji. Musi to być domena/adres ogólnie dostępny.

**Comment by ama93** [comment]
Dziękuję za odpowiedź. Ten sam problem mam pod domeną właściwą wrzuciłem natomiast tylko z localhosta screen. Miałbym pytanie gdzie może leżeć problem. Tak jak pisałem transakcja odbywa się poprawnie natomiast ta notyfikacja wysyłana POST zwraca 0. Nie wiem za bradzo co muszę poprawić jak zdebugować problem. Ostatnio zmieniłem wordpress na 5.4 i serwer na nginx z hostingu, może brakuje czegos na serwerze? Sam endpoint zwraca status 200 i resposne : 0. Z góry dziękuję.
