### ISSUE TITLE
Wystąpił błąd: (0) cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by gkurdej** [dotpay/WooCommerce2#76]
Witam,

w Wordpress 5.5+ wtyczka powoduje błąd, jak poniżej, widoczny w Narzędzia->Stan witryny. Nie wiem, co z tego powodu nie działa, ale na pewno spowalnia nawigację po zapleczu WP, np. wejście do Kokpitu trwa ponad 10 s (czas timeoutu, który widać w komunikacie błędu). Po wyłączeniu wtyczki błąd znika. Wtyczka w wersji 3.5.2, najnowszy WP i Woocommerce.

Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Wystąpił błąd: (0) cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received

**Comment by wpawel** [comment]
Problem nie powinien występować w wersji wtyczki >3.5.0. Proszę usunąć cały folder wtyczki z serwera i zainstalować na nowo najnowszą wersję [v3.5.3](https://github.com/dotpay/WooCommerce2/releases)

**Comment by gkurdej** [comment]
Po zainstalowaniu nowej wersji były przez chwilę dwie takie same wtyczki na liście, ale jedną usunąłem, wyłączyłem, włączyłem i zaczęło działać. Wersja 3.5.2 też tak miała - zaczynała działać poprawnie po instalacji dopiero jak się ją wyłączyło i włączyło ponownie. W każdym razie teraz jest ok. Dziękuję za pomoc.

**Comment by wpawel** [comment]
Dziękuję za potwierdzenie.
