### ISSUE TITLE
Checkout przekierowuje do pustego koszyka, w panelu nie widać uruchomionej bramki

### ISSUE THREAD

**Issue by danio987** [dotpay/WooCommerce2#8]
Witam,

Korzystam z wordpress w wersji 4.5.3 i woocommerce 2.6.4. Staram się włączyć wtyczkę ale nie pokazuje się w panelu że jest włączona.

![panel](https://cloud.githubusercontent.com/assets/4320973/17961014/8e6186ec-6aa9-11e6-81a1-4f2c903ae2ac.png)

 Natomiast kiedy włączę płatności blik lub inne widać że są włączone. 

![panel2](https://cloud.githubusercontent.com/assets/4320973/17961034/bf4994ac-6aa9-11e6-9eb2-26791667abbf.png)

I podczas akcji takiej:
1. Dodanie produktu do koszyka
2. Po przejściu do koszyka widać produkt
3. Przechodzę do kup i zapłać
4. zaznaczam metodę płatności (nie widać dotpay)
5. po kliknięciu Kup i Zapłać przenosi mnie do pustego koszyka z takim komunikatem

![checkout](https://cloud.githubusercontent.com/assets/4320973/17961137/3d8e1824-6aaa-11e6-815e-7086dcb3d13e.png)

Proszę o pomoc w tej sprawie

**Comment by tbajorek** [comment]
Witam,
czy problem występuje także po zainstalowaniu najnowszej wersji wtyczki?

**Comment by danio987** [comment]
Sprawa jest już załatwiona :)
Aktualizacja załatwiła sprawę.

Pozdrawiam.

2016-11-09 14:06 GMT+01:00 tbajorek <notifications@github.com>:
