### ISSUE TITLE
New certificate

### ISSUE THREAD

**Issue by morris4ever69** [dotpay/WooCommerce2#81]
Hello. We received an email from DotPay informing us that there will be a new certificate for the domain http://ssl.dotpay.pl/. Do we have to do (change or update) something in the website where the plugin is installed? Thanks.

**Comment by wpawel** [comment]
Hi, no, you don't need to do anything if you haven't had to update third party certificates on your server so far.
Plugin itself doesn't require anything like that.

**Comment by morris4ever69** [comment]
Ok, thank you!
