### ISSUE TITLE
Wtyczka wersja 3.7.1 a po zainstalowaniu wciąż wersja 3.7.0

### ISSUE THREAD

**Issue by flyjacki** [dotpay/WooCommerce2#89]
Coś chyba jest nie tak. Po zainstalowaniu nowej wersji (3.7.1) wtyczka pokazuje że jest w wersji 3.7.0 - brak zmian

**Comment by maciekmas** [comment]
Podbijam
w kodzie nadal jest 

 * @wordpress-plugin
  * Plugin Name: WooCommerce Dotpay Gateway
  * Version: 3.7.0
  
  oraz 
 $thisVersionModule = '3.7.0';
