### ISSUE TITLE
Miniaturki opcji płatności nie działają

### ISSUE THREAD

**Issue by JurekSIN** [dotpay/WooCommerce2#9]
![capturfiles_1000](https://cloud.githubusercontent.com/assets/24252068/20727938/b705ec28-b67b-11e6-8f5f-e8c734312efc.png)

**Comment by tbajorek** [comment]
Poproszę o adres niedziałającego obrazka. Chodzi mi o jego lokalizację. Bez innych informacji trudno jest nam rozwiązać ten problem.

**Comment by JurekSIN** [comment]
Np. dotpay.png - https://shop.sin.org.pl/pl/zamowienie/WOOCOMMERCE_DOTPAY_GATEWAY_URLresources/images/dotpay.png

Bez /pl/ też nie działa.

**Comment by JurekSIN** [comment]
Dzien dobry, czy bug bedzie zalatany?

**Comment by JurekSIN** [comment]
Dzien dobry, czy bug bedzie zalatany?  W nowej wersji wtyczki nadal wystepuje.

**Comment by tbajorek** [comment]
Proszę spróbować najnowszą wersję wtyczki:
[https://github.com/dotpay/WooCommerce2/releases/latest](https://github.com/dotpay/WooCommerce2/releases/latest)

Jeśli nadal nie działa, proszę napisać, jakiej wersji WP oraz WC Pan używa.

**Comment by JurekSIN** [comment]
Bangla! 

Serdecznie dziękuję i życzę miłego dnia. Dobra robota!

Pozdrawiam,
Jurek
